feat: networkStatus mockup data
Megalotron/Dashboard pull request #25
Opened 2021-12-13 16:38 UTC by QuentinFringhian

Description

This pull request in to instance the network status part of the network using mock up data

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added at least 1 reviewer
- [ ] I have tested this code
- [ ] I have added sufficient documentation in the code

# Additional comments

This is a mockup, it will have to be replace later.

2021-12-13 16:46 UTC, TomChv requested changes
A little mistake but it's looks good overall

2021-12-13 16:46 UTC, TomChv commented on dashboard/src/components/widgets/dashboard/networkSpeedWidget.tsx
> +import DownloadIcon from "../../../assests/icon/download.svg";
`assests` ??? 

And is it possible to create a file named `index.ts` that take care of aggregating all assets imports? It will make your import path much cleaner

2021-12-13 16:51 UTC, QuentinFringhian commented on dashboard/src/components/widgets/dashboard/networkSpeedWidget.tsx
> +import DownloadIcon from "../../../assests/icon/download.svg";
shize, this folder comes from an older merge :/ I will have to create another branch to fix this, maybe a branch 'fix/assets-folder' and here I will create your index.ts file, what do you think about that ?

2021-12-13 17:52 UTC, TomChv commented on dashboard/src/components/widgets/dashboard/networkSpeedWidget.tsx
> +import DownloadIcon from "../../../assests/icon/download.svg";
Ok, looks go

2021-12-14 11:08 UTC, TomChv commented
You can merge it when the CI is good

2021-12-14 16:27 UTC, merged